// Code generated by goyacc -v y.output -o parser.go -p mtail parser.y. DO NOT EDIT.

//line parser.y:5
/* #nosec G104 generated code, errors reported do not make sense */
package parser

import (
	"time"

	"github.com/google/mtail/internal/metrics"
	"github.com/google/mtail/internal/runtime/compiler/ast"
	"github.com/google/mtail/internal/runtime/compiler/position"
	//line parser.y:6
)

//line parser.y:19
type mtailSymType struct {
	yys      int
	intVal   int64
	floatVal float64
	floats   []float64
	op       int
	text     string
	texts    []string
	flag     bool
	n        ast.Node
	kind     metrics.Kind
	duration time.Duration
}

const INVALID = 57346
const COUNTER = 57347
const GAUGE = 57348
const TIMER = 57349
const TEXT = 57350
const HISTOGRAM = 57351
const AFTER = 57352
const AS = 57353
const BY = 57354
const CONST = 57355
const HIDDEN = 57356
const DEF = 57357
const DEL = 57358
const NEXT = 57359
const OTHERWISE = 57360
const ELSE = 57361
const STOP = 57362
const BUCKETS = 57363
const LIMIT = 57364
const BUILTIN = 57365
const REGEX = 57366
const STRING = 57367
const CAPREF = 57368
const CAPREF_NAMED = 57369
const ID = 57370
const DECO = 57371
const INTLITERAL = 57372
const FLOATLITERAL = 57373
const DURATIONLITERAL = 57374
const INC = 57375
const DEC = 57376
const DIV = 57377
const MOD = 57378
const MUL = 57379
const MINUS = 57380
const PLUS = 57381
const POW = 57382
const SHL = 57383
const SHR = 57384
const LT = 57385
const GT = 57386
const LE = 57387
const GE = 57388
const EQ = 57389
const NE = 57390
const BITAND = 57391
const XOR = 57392
const BITOR = 57393
const NOT = 57394
const AND = 57395
const OR = 57396
const ADD_ASSIGN = 57397
const ASSIGN = 57398
const MATCH = 57399
const NOT_MATCH = 57400
const LCURLY = 57401
const RCURLY = 57402
const LPAREN = 57403
const RPAREN = 57404
const LSQUARE = 57405
const RSQUARE = 57406
const COMMA = 57407
const NL = 57408

var mtailToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INVALID",
	"COUNTER",
	"GAUGE",
	"TIMER",
	"TEXT",
	"HISTOGRAM",
	"AFTER",
	"AS",
	"BY",
	"CONST",
	"HIDDEN",
	"DEF",
	"DEL",
	"NEXT",
	"OTHERWISE",
	"ELSE",
	"STOP",
	"BUCKETS",
	"LIMIT",
	"BUILTIN",
	"REGEX",
	"STRING",
	"CAPREF",
	"CAPREF_NAMED",
	"ID",
	"DECO",
	"INTLITERAL",
	"FLOATLITERAL",
	"DURATIONLITERAL",
	"INC",
	"DEC",
	"DIV",
	"MOD",
	"MUL",
	"MINUS",
	"PLUS",
	"POW",
	"SHL",
	"SHR",
	"LT",
	"GT",
	"LE",
	"GE",
	"EQ",
	"NE",
	"BITAND",
	"XOR",
	"BITOR",
	"NOT",
	"AND",
	"OR",
	"ADD_ASSIGN",
	"ASSIGN",
	"MATCH",
	"NOT_MATCH",
	"LCURLY",
	"RCURLY",
	"LPAREN",
	"RPAREN",
	"LSQUARE",
	"RSQUARE",
	"COMMA",
	"NL",
}

var mtailStatenames = [...]string{}

const mtailEofCode = 1
const mtailErrCode = 2
const mtailInitialStackSize = 16

//line parser.y:733

// tokenpos returns the position of the current token.
func tokenpos(mtaillex mtailLexer) position.Position {
	_ = "STUB: not implemented"
	return *new(position.Position)
}

// markedpos returns the position recorded from the most recent mark_pos
// production.
func markedpos(mtaillex mtailLexer) position.Position {
	_ = "STUB: not implemented"
	return *new(position.Position)
}

// positionFromMark returns a position spanning from the last mark to the current position.
func positionFromMark(mtaillex mtailLexer) position.Position {
	_ = "STUB: not implemented"
	return *new(position.Position)
}

//line yacctab:1
var mtailExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	5, 93,
	6, 93,
	7, 93,
	8, 93,
	9, 93,
	-2, 124,
	-1, 22,
	66, 24,
	-2, 68,
	-1, 106,
	5, 93,
	6, 93,
	7, 93,
	8, 93,
	9, 93,
	-2, 124,
}

const mtailPrivate = 57344

const mtailLast = 249

var mtailAct = [...]int{
	171, 88, 126, 28, 15, 91, 42, 44, 27, 30,
	103, 127, 41, 24, 20, 86, 40, 167, 22, 128,
	163, 182, 19, 26, 45, 29, 104, 25, 36, 34,
	35, 43, 54, 38, 39, 87, 181, 85, 89, 125,
	108, 46, 36, 34, 35, 43, 47, 38, 39, 90,
	162, 163, 62, 63, 2, 31, 49, 87, 76, 77,
	68, 130, 74, 73, 37, 138, 62, 63, 50, 112,
	93, 94, 117, 97, 96, 118, 168, 50, 37, 119,
	120, 70, 72, 71, 121, 122, 123, 66, 67, 124,
	107, 129, 185, 184, 111, 79, 80, 81, 82, 83,
	84, 169, 106, 131, 179, 135, 132, 175, 15, 133,
	129, 43, 27, 110, 100, 101, 99, 134, 20, 102,
	174, 135, 22, 173, 87, 129, 19, 160, 87, 151,
	156, 142, 155, 157, 158, 87, 87, 87, 164, 166,
	165, 161, 153, 159, 140, 154, 152, 136, 139, 178,
	177, 13, 141, 116, 66, 67, 115, 49, 105, 109,
	11, 23, 1, 176, 10, 129, 180, 12, 64, 145,
	13, 65, 36, 34, 35, 43, 75, 38, 39, 11,
	23, 98, 183, 10, 95, 69, 12, 92, 61, 78,
	18, 36, 34, 35, 43, 170, 38, 39, 143, 31,
	56, 57, 58, 59, 60, 172, 144, 137, 37, 36,
	34, 35, 43, 16, 38, 39, 146, 55, 31, 33,
	51, 53, 114, 48, 9, 8, 7, 37, 49, 113,
	6, 32, 16, 21, 52, 17, 31, 148, 147, 5,
	50, 14, 4, 3, 0, 37, 0, 149, 150,
}

var mtailPact = [...]int{
	-1000, -1000, 166, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 83, -1000, -1000, -13, 205, -1000, -34, 195, 13,
	13, -1000, 54, -1000, 21, 32, -1000, 7, 1, -1000,
	52, 184, -25, -1000, -1000, -1000, -1000, 184, -1000, -1000,
	29, -1000, 35, -1000, 79, -40, 139, -1000, -13, -21,
	-1000, 85, -13, 17, -1000, 128, -1000, -1000, -1000, -1000,
	-1000, -40, -1000, -1000, -40, -1000, -1000, -1000, -40, -40,
	-1000, -1000, -1000, -40, -40, -40, -1000, -1000, -40, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 54, -1000, 134, 184,
	-1, -1000, -40, -1000, -1000, -40, -1000, -1000, -40, -1000,
	-1000, -1000, -1000, -1000, -1000, -13, 147, -1000, 3, 120,
	-13, -1000, 121, 226, -1000, -1000, -1000, 184, 184, 83,
	184, 184, 184, 17, 184, -14, -1000, 13, -1000, 33,
	-1000, 184, 184, 184, 21, 42, -1000, -1000, -1000, -45,
	41, -1000, 69, -1000, -1000, -1000, -1000, 95, 82, 119,
	74, 13, 32, -1000, -1000, -1000, 52, 13, 13, -1000,
	-1000, 29, -1000, 184, 35, 79, -1000, -1000, -1000, -1000,
	-29, -1000, -1000, -1000, -1000, -1000, -44, -1000, -1000, -1000,
	-1000, 95, 62, -1000, -1000, -1000,
}

var mtailPgo = [...]int{
	0, 54, 243, 39, 41, 242, 241, 239, 235, 3,
	7, 6, 15, 5, 233, 9, 16, 27, 11, 231,
	12, 13, 19, 230, 229, 226, 225, 25, 23, 224,
	222, 219, 2, 217, 216, 206, 205, 0, 198, 195,
	190, 189, 187, 185, 168, 184, 181, 176, 171, 169,
	163, 162, 10, 1, 159,
}

var mtailR1 = [...]int{
	0, 51, 1, 1, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 5, 5, 5, 6, 6, 6,
	7, 7, 4, 8, 8, 14, 14, 18, 18, 18,
	18, 44, 44, 17, 17, 43, 43, 43, 15, 15,
	41, 41, 41, 41, 41, 41, 16, 16, 42, 42,
	11, 11, 45, 45, 28, 28, 47, 47, 22, 21,
	21, 21, 10, 10, 46, 46, 46, 46, 13, 13,
	12, 12, 48, 48, 9, 9, 9, 9, 9, 9,
	9, 9, 19, 19, 20, 31, 31, 3, 3, 32,
	32, 27, 23, 40, 40, 24, 24, 24, 24, 24,
	30, 30, 33, 33, 33, 33, 33, 38, 39, 39,
	37, 35, 34, 49, 50, 50, 50, 50, 25, 26,
	29, 29, 36, 36, 53, 54, 52, 52,
}

var mtailR2 = [...]int{
	0, 1, 0, 2, 1, 1, 1, 1, 1, 1,
	1, 4, 1, 1, 4, 2, 3, 1, 4, 1,
	1, 2, 3, 1, 1, 4, 4, 1, 1, 4,
	4, 1, 1, 1, 4, 1, 1, 1, 1, 4,
	1, 1, 1, 1, 1, 1, 1, 4, 1, 1,
	1, 4, 1, 1, 4, 4, 1, 1, 1, 1,
	4, 4, 1, 4, 1, 1, 1, 1, 1, 2,
	1, 2, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 1, 1, 4, 1, 4, 5, 1, 3, 1,
	1, 5, 3, 0, 1, 2, 2, 2, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 3,
	1, 2, 2, 2, 1, 1, 3, 3, 4, 3,
	5, 3, 1, 1, 0, 0, 0, 1,
}

var mtailChk = [...]int{
	-1000, -51, -1, -2, -5, -7, -23, -25, -26, -29,
	17, 13, 20, 4, -6, -53, 66, -8, -40, -22,
	-18, -14, -12, 14, -21, -17, -28, -13, -9, -27,
	-15, 52, -19, -31, 26, 27, 25, 61, 30, 31,
	-16, -20, -11, 28, -10, -20, -4, 59, 18, 23,
	35, 15, 29, 16, 66, -33, 5, 6, 7, 8,
	9, -44, 53, 54, -44, -48, 33, 34, 39, -43,
	49, 51, 50, 56, 55, -47, 57, 58, -41, 43,
	44, 45, 46, 47, 48, -13, -12, -9, -53, 63,
	-18, -13, -42, 41, 42, -45, 39, 38, -46, 37,
	35, 36, 40, -52, 66, 19, -1, -4, 61, -54,
	28, -4, -12, -24, -30, 28, 25, -52, -52, -52,
	-52, -52, -52, -52, -52, -3, -32, -18, -22, -53,
	62, -52, -52, -52, -21, -53, -4, 60, 62, -3,
	24, -4, 10, -38, -35, -49, -34, 12, 11, 21,
	22, -18, -17, -28, -27, -20, -15, -18, -18, -22,
	-9, -16, 64, 65, -11, -10, -13, 62, 35, 32,
	-39, -37, -36, 28, 25, 25, -50, 31, 30, 30,
	-32, 65, 65, -37, 31, 30,
}

var mtailDef = [...]int{
	2, -2, -2, 3, 4, 5, 6, 7, 8, 9,
	10, 0, 12, 13, 0, 0, 20, 0, 0, 17,
	19, 23, -2, 94, 58, 27, 28, 62, 70, 59,
	33, 124, 74, 75, 76, 77, 78, 124, 80, 81,
	38, 82, 46, 84, 50, 126, 15, 2, 0, 0,
	125, 0, 0, 124, 21, 0, 102, 103, 104, 105,
	106, 126, 31, 32, 126, 71, 72, 73, 126, 126,
	35, 36, 37, 126, 126, 126, 56, 57, 126, 40,
	41, 42, 43, 44, 45, 69, 68, 70, 0, 124,
	0, 62, 126, 48, 49, 126, 52, 53, 126, 64,
	65, 66, 67, 124, 127, 0, -2, 16, 124, 0,
	0, 119, 121, 92, 99, 100, 101, 124, 124, 124,
	124, 124, 124, 124, 124, 0, 87, 89, 90, 0,
	79, 124, 124, 124, 11, 0, 14, 22, 85, 0,
	0, 118, 0, 95, 96, 97, 98, 0, 0, 0,
	0, 18, 29, 30, 60, 61, 34, 25, 26, 54,
	55, 39, 83, 124, 47, 51, 63, 86, 91, 120,
	107, 108, 110, 122, 123, 111, 113, 114, 115, 112,
	88, 0, 0, 109, 116, 117,
}

var mtailTok1 = [...]int{
	1,
}

var mtailTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66,
}

var mtailTok3 = [...]int{
	0,
}

var mtailErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
	{109, 4, "unexpected end of file, expecting '/' to end regex"},
	{15, 1, "unexpected end of file, expecting '}' to end block"},
	{15, 1, "unexpected end of file, expecting '}' to end block"},
	{15, 1, "unexpected end of file, expecting '}' to end block"},
	{14, 63, "unexpected indexing of an expression"},
	{14, 66, "statement with no effect, missing an assignment, `+' concatenation, or `{}' block?"},
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	mtailDebug        = 0
	mtailErrorVerbose = false
)

type mtailLexer interface {
	Lex(lval *mtailSymType) int
	Error(s string)
}

type mtailParser interface {
	Parse(mtailLexer) int
	Lookahead() int
}

type mtailParserImpl struct {
	lval  mtailSymType
	stack [mtailInitialStackSize]mtailSymType
	char  int
}

func (p *mtailParserImpl) Lookahead() int { _ = "STUB: not implemented"; return 0 }

func mtailNewParser() mtailParser { _ = "STUB: not implemented"; return *new(mtailParser) }

const mtailFlag = -1000

func mtailTokname(c int) string { _ = "STUB: not implemented"; return "" }

func mtailStatname(s int) string { _ = "STUB: not implemented"; return "" }

func mtailErrorMessage(state, lookAhead int) string { _ = "STUB: not implemented"; return "" }

// To match Bison, suggest at most four expected tokens.

// Look for shiftable tokens.

// Look for tokens that we accept or reduce.

// If the default action is to accept or reduce, give up.

func mtaillex1(lex mtailLexer, lval *mtailSymType) (char, token int) {
	_ = "STUB: not implemented"
	return 0, 0
}

/* unknown char */

func mtailParse(mtaillex mtailLexer) int { _ = "STUB: not implemented"; return 0 }

func (mtailrcvr *mtailParserImpl) Parse(mtaillex mtailLexer) int {
	_ = "STUB: not implemented"
	return 0
}

// silence set and not used

/* number of errors */
/* error recovery flag */

// mtailrcvr.char translated into internal numbering

// Make sure we report no lookahead when not parsing.

/* put a state and value onto the stack */

/* simple state */

/* valid shift */

/* default state action */

/* look through exception table */

/* error ... attempt to resume parsing */

/* brand new error */

/* incompletely recovered error ... try again */

/* find a state where "error" is a legal shift action */

/* simulate a shift of "error" */

/* the current p has no shift on "error", pop stack */

/* there is no state on the stack with an error shift ... abort */

/* no shift yet; clobber input char */

/* try again in the same state */

/* reduction by production mtailn */

// guard against "declared and not used"

// mtailp is now the index of $0. Perform the default action. Iff the
// reduced production is ε, $1 is possibly out of range.

/* consult goto table to find next state */

// dummy call; replaced with literal code

//line parser.y:93

//line parser.y:101

//line parser.y:105

//line parser.y:116

//line parser.y:118

//line parser.y:120

//line parser.y:122

//line parser.y:124

//line parser.y:126

//line parser.y:128

//line parser.y:132

//line parser.y:136

//line parser.y:140

//line parser.y:148

//line parser.y:152

//line parser.y:160

//line parser.y:168

//line parser.y:172

//line parser.y:180

//line parser.y:186

//line parser.y:188

//line parser.y:194

//line parser.y:202

//line parser.y:204

//line parser.y:210

//line parser.y:214

//line parser.y:222

//line parser.y:224

//line parser.y:226

//line parser.y:230

//line parser.y:237

//line parser.y:239

//line parser.y:245

//line parser.y:247

//line parser.y:254

//line parser.y:256

//line parser.y:258

//line parser.y:264

//line parser.y:266

//line parser.y:273

//line parser.y:275

//line parser.y:277

//line parser.y:279

//line parser.y:281

//line parser.y:283

//line parser.y:289

//line parser.y:291

//line parser.y:298

//line parser.y:300

//line parser.y:306

//line parser.y:308

//line parser.y:315

//line parser.y:317

//line parser.y:323

//line parser.y:327

//line parser.y:334

//line parser.y:336

//line parser.y:343

//line parser.y:351

//line parser.y:353

//line parser.y:357

//line parser.y:365

//line parser.y:367

//line parser.y:374

//line parser.y:376

//line parser.y:378

//line parser.y:380

//line parser.y:386

//line parser.y:388

//line parser.y:396

//line parser.y:398

//line parser.y:405

//line parser.y:407

//line parser.y:413

//line parser.y:415

//line parser.y:417

//line parser.y:421

//line parser.y:425

//line parser.y:429

//line parser.y:433

//line parser.y:437

//line parser.y:445

// Build an empty IndexedExpr so that the recursive rule below doesn't need to handle the alternative.

//line parser.y:450

//line parser.y:461

//line parser.y:469

//line parser.y:473

//line parser.y:482

//line parser.y:487

//line parser.y:495

//line parser.y:497

//line parser.y:503

//line parser.y:511

//line parser.y:522

//line parser.y:526

//line parser.y:534

//line parser.y:539

//line parser.y:544

//line parser.y:549

//line parser.y:554

//line parser.y:562

//line parser.y:566

//line parser.y:574

//line parser.y:578

//line parser.y:582

//line parser.y:586

//line parser.y:590

//line parser.y:598

//line parser.y:605

//line parser.y:610

//line parser.y:618

//line parser.y:624

//line parser.y:631

//line parser.y:639

//line parser.y:645

//line parser.y:650

//line parser.y:655

//line parser.y:660

//line parser.y:668

//line parser.y:676

//line parser.y:684

//line parser.y:688

//line parser.y:695

//line parser.y:699

//line parser.y:709

//line parser.y:719

/* stack new state and value */
